import AppKit
import Carbon
import DictationCore

/// NSPasteboard.general as a DictationPasteboard.
///
/// With `promised`, dictated text is written as a promise: the pasteboard asks
/// this app for the text when another app reads it, and `readAt` records when
/// that happened, which tells PasteOutput the paste has been taken. It is also
/// marked transient, so clipboard managers leave it out of their history.
final class SystemPasteboard: NSObject, DictationPasteboard, NSPasteboardItemDataProvider {
    private let pasteboard = NSPasteboard.general
    private let promised: Bool
    private var text = ""
    /// When an app first read the promised text since the last write.
    private(set) var readAt: Date?

    init(promised: Bool) {
        self.promised = promised
    }

    var changeCount: Int { pasteboard.changeCount }

    func snapshot() -> PasteboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item -> [String: Data] in
            var types: [String: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) { types[type.rawValue] = data }
            }
            return types
        }
        return PasteboardSnapshot(items: items)
    }

    @discardableResult
    func writeText(_ text: String) -> Int {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        if promised {
            self.text = text
            readAt = nil
            item.setDataProvider(self, forTypes: [.string])
            item.setData(Data(), forType: NSPasteboard.PasteboardType(PasteboardMarker.transient))
        } else {
            item.setString(text, forType: .string)
        }
        item.setData(Data(), forType: NSPasteboard.PasteboardType(PasteboardMarker.autoGenerated))
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    func restore(_ snapshot: PasteboardSnapshot) {
        pasteboard.clearContents()
        let items = snapshot.items.map { types -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in types { item.setData(data, forType: NSPasteboard.PasteboardType(type)) }
            // The user's copy is already in any clipboard history; putting it back
            // is not a new copy.
            item.setData(Data(), forType: NSPasteboard.PasteboardType(PasteboardMarker.transient))
            return item
        }
        if !items.isEmpty { pasteboard.writeObjects(items) }
    }

    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        if readAt == nil { readAt = Date() }
        item.setString(text, forType: type)
    }
}

/// Puts dictated text where the cursor is: borrows the clipboard, sends Cmd+V to
/// the frontmost app and gives the clipboard back once the app has read it. When
/// pasting is not allowed or not safe, the text stays on the clipboard and
/// `onNotice` says why.
final class PasteOutput: TextOutput {
    var onNotice: ((String) -> Void)?
    /// The app that had focus when the recording stopped; the paste goes there
    /// or nowhere.
    var target: pid_t?

    private let lending = SystemPasteboard(promised: true)
    private let plain = SystemPasteboard(promised: false)
    /// A paste whose clipboard has not been given back yet.
    private var pending: (lease: ClipboardLease, timer: Timer)?

    func deliver(_ text: String) {
        // A previous paste still waiting for its read: give its clipboard back
        // now, so this one borrows the user's contents and not the old dictation.
        settle()
        let front = NSWorkspace.shared.frontmostApplication?.processIdentifier
        let moved = target != nil && front != target
        switch OutputPolicy.decide(secureInput: IsSecureEventInputEnabled(), focusMoved: moved,
                                   accessibilityTrusted: AXIsProcessTrusted()) {
        case .clipboardOnly(let reason):
            plain.writeText(text)
            onNotice?(reason)
        case .paste:
            let lease = ClipboardLease(board: lending, text: text)
            let posted = Date()
            postCommandV()
            // Give the clipboard back once the app has read the text and had a
            // moment to finish the paste; if it never reads it (the field takes no
            // paste), after 3 s. Restoring before the read would paste the user's
            // previous clipboard instead of the dictation.
            let timer = Timer.scheduledTimer(withTimeInterval: 0.05, repeats: true) { [weak self, lending] _ in
                let now = Date()
                let read = lending.readAt.map { now.timeIntervalSince($0) >= 0.2 } ?? false
                if (read && now.timeIntervalSince(posted) >= 0.3) || now.timeIntervalSince(posted) >= 3 {
                    self?.settle()
                }
            }
            pending = (lease, timer)
        }
    }

    private func settle() {
        guard let pending else { return }
        self.pending = nil
        pending.timer.invalidate()
        pending.lease.release()
    }

    private func postCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let v = CGKeyCode(kVK_ANSI_V)
        // Only Command: a modifier still held from the hotkey must not turn this into ⌃⌘V.
        let down = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: true)
        down?.flags = .maskCommand
        let up = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: false)
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }
}
