import AppKit
import Carbon
import DictationCore

/// NSPasteboard.general as a DictationPasteboard.
///
/// With `promised`, dictated text is written as a promise: the pasteboard asks
/// this app for the text when another app reads it, and `readAt` records when
/// that happened, which tells PasteOutput the paste has been taken. It is also
/// marked transient, so clipboard managers leave it out of their history.
final class SystemPasteboard: NSObject, DictationPasteboard, NSPasteboardItemDataProvider {
    private let pasteboard = NSPasteboard.general
    private let promised: Bool
    private var text = ""
    /// When an app first read the promised text since the last write.
    private(set) var readAt: Date?

    init(promised: Bool) {
        self.promised = promised
    }

    var changeCount: Int { pasteboard.changeCount }

    var declaredItems: [[String]] {
        (pasteboard.pasteboardItems ?? []).map { $0.types.map(\.rawValue) }
    }

    func data(item index: Int, forType type: String) -> Data? {
        guard let items = pasteboard.pasteboardItems, items.indices.contains(index) else { return nil }
        return items[index].data(forType: NSPasteboard.PasteboardType(type))
    }

    @discardableResult
    func writeText(_ text: String) -> Int {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        if promised {
            self.text = text
            readAt = nil
            item.setDataProvider(self, forTypes: [.string])
            item.setData(Data(), forType: NSPasteboard.PasteboardType(PasteboardMarker.transient))
        } else {
            item.setString(text, forType: .string)
        }
        item.setData(Data(), forType: NSPasteboard.PasteboardType(PasteboardMarker.autoGenerated))
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    func restore(_ snapshot: PasteboardSnapshot) {
        pasteboard.clearContents()
        let items = snapshot.items.map { entries -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for entry in entries { item.setData(entry.data, forType: NSPasteboard.PasteboardType(entry.type)) }
            // The user's copy is already in any clipboard history; putting it back
            // is not a new copy.
            for marker in PasteboardMarker.restored { item.setData(Data(), forType: NSPasteboard.PasteboardType(marker)) }
            return item
        }
        if !items.isEmpty { pasteboard.writeObjects(items) }
    }

    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        if readAt == nil { readAt = Date() }
        item.setString(text, forType: type)
    }
}

/// Puts dictated text where the cursor is: borrows the clipboard, sends Cmd+V to
/// the frontmost app and gives the clipboard back once the app has read it. When
/// pasting is not allowed or not safe, the text stays on the clipboard and
/// `onNotice` says why.
final class PasteOutput: TextOutput {
    var onNotice: ((String) -> Void)?
    /// The app that had focus when the recording stopped; the paste goes there
    /// or nowhere.
    var target: pid_t?

    private let lending = SystemPasteboard(promised: true)
    private let plain = SystemPasteboard(promised: false)
    /// A paste whose clipboard has not been given back yet.
    private var pending: (lease: ClipboardLease, timer: Timer, text: String)?

    func deliver(_ text: String) {
        // A previous paste still waiting for its read: give its clipboard back
        // now, so this one borrows the user's contents and not the old dictation.
        settle()
        let front = NSWorkspace.shared.frontmostApplication?.processIdentifier
        let moved = target != nil && front != target
        switch OutputPolicy.decide(secureInput: IsSecureEventInputEnabled(), focusMoved: moved,
                                   accessibilityTrusted: AXIsProcessTrusted()) {
        case .clipboardOnly(let reason):
            plain.writeText(text)
            onNotice?(reason)
        case .paste:
            let lease = ClipboardLease(board: lending, text: text)
            let posted = Date()
            postCommandV()
            // Give the clipboard back once the app has read the text and had a
            // moment to finish the paste; if it never reads it (the field takes no
            // paste), after 3 s. Restoring before the read would paste the user's
            // previous clipboard instead of the dictation.
            let timer = Timer.scheduledTimer(withTimeInterval: 0.05, repeats: true) { [weak self, lending] _ in
                let now = Date()
                let read = lending.readAt.map { now.timeIntervalSince($0) >= 0.2 } ?? false
                if (read && now.timeIntervalSince(posted) >= 0.3) || now.timeIntervalSince(posted) >= 3 {
                    self?.settle()
                }
            }
            pending = (lease, timer, text)
        }
    }

    /// Gives a borrowed clipboard back now. Also called before the app quits: the
    /// promised text dies with the process and would leave the clipboard empty.
    func settle() {
        guard let pending else { return }
        self.pending = nil
        pending.timer.invalidate()
        if !pending.lease.release(), let notice = pending.lease.notice {
            // The user's clipboard is not coming back, so the dictation stays on
            // it. Write it plainly: the lent copy is a transient promise, which
            // clipboard history skips and which dies with this process.
            plain.writeText(pending.text)
            onNotice?(notice)
        }
    }

    private func postCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let v = CGKeyCode(PasteKey.commandV(lookup: PasteOutput.layoutCharacter()))
        // Only Command: a modifier still held from the hotkey must not turn this into ⌃⌘V.
        let down = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: true)
        down?.flags = .maskCommand
        let up = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: false)
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    /// Maps a virtual key code to the character it types with ⌘ held in the
    /// current keyboard layout, via UCKeyTranslate on the live TIS layout data.
    /// ⌘ matters: some layouts switch tables under it ("Dvorak – QWERTY ⌘"
    /// types QWERTY, Russian types Latin). The closure holds the layout bytes, so one paste scans the
    /// keyboard once. A dead key or a key that types nothing maps to nil, as
    /// does every key when the layout cannot be read at all.
    private static func layoutCharacter() -> (Int) -> Character? {
        guard let data = layoutData() else { return { _ in nil } }
        let keyboardType = UInt32(LMGetKbdType())
        return { keyCode in
            data.withUnsafeBytes { raw -> Character? in
                guard let layout = raw.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return nil }
                var deadKeyState: UInt32 = 0
                var length = 0
                var chars = [UniChar](repeating: 0, count: 4)
                let commandHeld = UInt32((cmdKey >> 8) & 0xFF)
                guard UCKeyTranslate(layout, UInt16(keyCode), UInt16(kUCKeyActionDown), commandHeld,
                                     keyboardType, UInt32(kUCKeyTranslateNoDeadKeysMask),
                                     &deadKeyState, chars.count, &length, &chars) == noErr,
                      length > 0 else { return nil }
                return String(utf16CodeUnits: chars, count: length).first
            }
        }
    }

    /// The current layout's UCKeyTranslate data; the ASCII-capable layout's
    /// when the current input source does not carry key layout data.
    private static func layoutData() -> Data? {
        func uchr(_ source: TISInputSource?) -> Data? {
            guard let source, let ref = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
                return nil
            }
            // The CFData belongs to `source` (Get rule): bridge it while the
            // source is alive; the Data then keeps its own reference.
            return withExtendedLifetime(source) { Unmanaged<CFData>.fromOpaque(ref).takeUnretainedValue() as Data }
        }
        return uchr(TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue())
            ?? uchr(TISCopyCurrentASCIICapableKeyboardLayoutInputSource()?.takeRetainedValue())
    }
}
