import Foundation

/// The pasteboard as dictation output sees it: `NSPasteboard.general` in the app,
/// a fake in tests.
public protocol DictationPasteboard: AnyObject {
    /// Changes on every write to the pasteboard, by any app.
    var changeCount: Int { get }
    /// Every item with every type it carries, to be put back later.
    func snapshot() -> PasteboardSnapshot
    /// Replaces the contents with plain text and returns the resulting changeCount.
    @discardableResult func writeText(_ text: String) -> Int
    /// Replaces the contents with a snapshot.
    func restore(_ snapshot: PasteboardSnapshot)
}

/// The pasteboard contents: one dictionary per item, type identifier to data.
public struct PasteboardSnapshot: Equatable {
    public var items: [[String: Data]]
    public init(items: [[String: Data]]) { self.items = items }

    /// Marked by its writer as a secret (nspasteboard.org convention, used by
    /// password managers). Such contents are not put back.
    public var isSensitive: Bool {
        items.contains { item in PasteboardMarker.sensitive.contains { item.keys.contains($0) } }
    }
}

/// Type identifiers from nspasteboard.org that clipboard managers and password
/// managers agree on.
public enum PasteboardMarker {
    /// A secret, e.g. a password copied from a password manager.
    public static let concealed = "org.nspasteboard.ConcealedType"
    /// Short-lived: clipboard managers do not keep it in their history.
    public static let transient = "org.nspasteboard.TransientType"
    /// Written by software, not copied by the user.
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    /// Contents carrying any of these are a secret: not put back after a paste.
    public static let sensitive = [concealed]
    /// Added to the user's contents when they are put back: it is not a new copy,
    /// so clipboard managers skip it. Must not overlap `sensitive`, or the next
    /// dictation would take the restored contents for a secret and drop them.
    public static let restored = [autoGenerated]
}

/// Borrows the clipboard to deliver dictated text. It remembers what was there,
/// writes the text for a paste, and later puts the original back, but only if
/// nothing has written to the clipboard since. If the user copied something in the
/// meantime, or another app wrote to it, the clipboard is theirs now and restoring
/// would destroy their copy.
///
/// A secret (a password manager's copy) is never put back: a password manager
/// clears the clipboard later only if it still holds the manager's own write, so
/// restoring it would leave the password on the clipboard for good.
public final class ClipboardLease {
    private let board: DictationPasteboard
    private let original: PasteboardSnapshot
    private let ourChange: Int

    public init(board: DictationPasteboard, text: String) {
        self.board = board
        self.original = board.snapshot()
        self.ourChange = board.writeText(text)
    }

    /// Restores the original contents if the clipboard still holds our text.
    /// Returns whether it did. Only the first call can: restoring is a write.
    @discardableResult
    public func release() -> Bool {
        guard board.changeCount == ourChange else { return false }
        guard !original.isSensitive else { return false }
        board.restore(original)
        return true
    }
}
