import Foundation

/// The pasteboard as dictation output sees it: `NSPasteboard.general` in the app,
/// a fake in tests.
public protocol DictationPasteboard: AnyObject {
    /// Changes on every write to the pasteboard, by any app.
    var changeCount: Int { get }
    /// The type identifiers each item declares, in the item's own order.
    var declaredItems: [[String]] { get }
    /// The data behind a declared type of an item, or nil when the source
    /// cannot or will not give it. Only types PasteboardSnapshot asks for are
    /// read; promised types are never read through here.
    func data(item: Int, forType type: String) -> Data?
    /// Replaces the contents with plain text and returns the resulting changeCount.
    @discardableResult func writeText(_ text: String) -> Int
    /// Replaces the contents with a snapshot.
    func restore(_ snapshot: PasteboardSnapshot)
}

/// One type an item carried, with its data, kept in the item's declared order:
/// the order is the priority a reader picks formats by, so a restore must keep it.
public struct PasteboardEntry: Equatable {
    public var type: String
    public var data: Data
    public init(type: String, data: Data) {
        self.type = type
        self.data = data
    }
}

/// The pasteboard contents: the types of every item in each item's declared
/// order, with their data — plus the reasons the snapshot is not a whole copy.
public struct PasteboardSnapshot: Equatable {
    public var items: [[PasteboardEntry]]
    /// Why the snapshot is not exactly what the user had. Non-empty means it
    /// must not be put back: it would be a different clipboard, silently.
    public private(set) var problems: [String]
    /// Holding more than this for a restore costs more than the restore saves.
    public static let maxBytes = 64 * 1024 * 1024

    public init(items: [[PasteboardEntry]], problems: [String] = []) {
        self.items = items
        self.problems = problems
    }

    /// Copies every type of every item on `board`, in declared order.
    /// Promised types are never read: reading one runs the source app's
    /// provider synchronously, which can stall for seconds on a big promise.
    /// A promise and a clipboard over `maxBytes` go into `problems`: the
    /// snapshot then is not the user's copy, and putting it back would hand
    /// them a different clipboard without a word.
    /// A type that gives no data is left out without a problem: no app can
    /// paste it either, so the restore loses nothing a reader could get, and
    /// refusing the restore over it would throw away everything else.
    public static func capture(_ board: DictationPasteboard) -> PasteboardSnapshot {
        var snapshot = PasteboardSnapshot(items: [])
        var bytes = 0
        capture: for (index, types) in board.declaredItems.enumerated() {
            var entries: [PasteboardEntry] = []
            for type in types {
                if isPromisedType(type) {
                    snapshot.report("a promised file")
                    continue
                }
                guard let data = board.data(item: index, forType: type) else { continue }
                bytes += data.count
                if bytes > maxBytes {
                    snapshot.report("more than \(maxBytes / (1024 * 1024)) MB of data")
                    break capture
                }
                entries.append(PasteboardEntry(type: type, data: data))
            }
            snapshot.items.append(entries)
        }
        return snapshot
    }

    private mutating func report(_ problem: String) {
        if !problems.contains(problem) { problems.append(problem) }
    }

    /// A promised type carries no data until the source app is asked for it;
    /// asking runs the source's provider on this thread. Apple's promise UTIs
    /// all carry "promise" (com.apple.pasteboard.promised-file,
    /// com.apple.pasteboard.promised-file-url, com.apple.NSFilePromise).
    private static func isPromisedType(_ type: String) -> Bool {
        type.lowercased().contains("promise")
    }

    /// Marked by its writer as a secret (nspasteboard.org convention, used by
    /// password managers). Such contents are not put back.
    public var isSensitive: Bool {
        items.contains { item in item.contains { PasteboardMarker.sensitive.contains($0.type) } }
    }
}

/// Type identifiers from nspasteboard.org that clipboard managers and password
/// managers agree on.
public enum PasteboardMarker {
    /// A secret, e.g. a password copied from a password manager.
    public static let concealed = "org.nspasteboard.ConcealedType"
    /// Short-lived: clipboard managers do not keep it in their history.
    public static let transient = "org.nspasteboard.TransientType"
    /// Written by software, not copied by the user.
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    /// Contents carrying any of these are a secret: not put back after a paste.
    public static let sensitive = [concealed]
    /// Added to the user's contents when they are put back: it is not a new copy,
    /// so clipboard managers skip it. Must not overlap `sensitive`, or the next
    /// dictation would take the restored contents for a secret and drop them.
    public static let restored = [autoGenerated]
}

/// Borrows the clipboard to deliver dictated text. It remembers what was there,
/// writes the text for a paste, and later puts the original back, but only if
/// nothing has written to the clipboard since. If the user copied something in the
/// meantime, or another app wrote to it, the clipboard is theirs now and restoring
/// would destroy their copy.
///
/// A secret (a password manager's copy) is never put back: a password manager
/// clears the clipboard later only if it still holds the manager's own write, so
/// restoring it would leave the password on the clipboard for good.
public final class ClipboardLease {
    private let board: DictationPasteboard
    private let original: PasteboardSnapshot
    private let ourChange: Int
    /// Why `release` left our text instead of putting the original back: the
    /// snapshot was not a whole copy of what the user had. nil when the
    /// clipboard was left because someone else wrote to it — that copy is the
    /// user's own.
    public private(set) var notice: String?

    public init(board: DictationPasteboard, text: String) {
        self.board = board
        self.original = PasteboardSnapshot.capture(board)
        self.ourChange = board.writeText(text)
    }

    /// Restores the original contents if the clipboard still holds our text.
    /// Returns whether it did. Only the first call can: restoring is a write.
    @discardableResult
    public func release() -> Bool {
        guard board.changeCount == ourChange else { return false }
        guard !original.isSensitive else { return false }
        guard original.problems.isEmpty else {
            notice = "The earlier clipboard was not put back: it held \(original.problems.joined(separator: " and ")). The dictated text is on the clipboard."
            return false
        }
        board.restore(original)
        return true
    }
}
